<a href="https://colab.research.google.com/github/ajithosh229/MACHINE-LEARNING/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**WEEK-8**

---

**K-Nearest Neighbors Algorithm**

---

*M.Ajithosh - 24911A6699*

---

*CSE(AIML-B)*

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
df = pd.read_csv('/content/drive/MyDrive/iris.csv')

In [4]:
print (df.shape)
(150,5)

(150, 5)


(150, 5)

In [5]:
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [6]:
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [7]:
print(df.species)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [9]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(df.species)
df['species'] = le.transform(df.species)
print(df)

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]


In [10]:
print(df.species)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64


In [11]:
X=df.iloc[:,0:4]

In [12]:
X

,sepal_length,sepal_width,petal_length,petal_width
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [13]:
Y=df.iloc[:,4]

In [14]:
Y

,species
0,0
1,0
2,0
3,0
4,0
...,...
145,2
146,2
147,2
148,2


In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.70,random_state=123)

In [16]:
print(X_train.shape)

(45, 4)


In [17]:
print(X_test.shape)

(105, 4)


In [18]:
print(Y_test.shape)

(105,)


In [19]:
print(Y_train.shape)

(45,)


In [20]:
X_train

,sepal_length,sepal_width,petal_length,petal_width
76,6.8,2.8,4.8,1.4
134,6.1,2.6,5.6,1.4
34,4.9,3.1,1.5,0.1
27,5.2,3.5,1.5,0.2
94,5.6,2.7,4.2,1.3
85,6.0,3.4,4.5,1.6
97,6.2,2.9,4.3,1.3
102,7.1,3.0,5.9,2.1
52,6.9,3.1,4.9,1.5
92,5.8,2.6,4.0,1.2


In [21]:
Y_train

,species
76,1
134,2
34,0
27,0
94,1
85,1
97,1
102,2
52,1
92,1


In [22]:
model = KNeighborsClassifier(n_neighbors=3)

In [23]:
model

KNeighborsClassifier(n_neighbors=3)

In [24]:
model_train = model.fit(X_train,Y_train)

In [25]:
model_train

KNeighborsClassifier(n_neighbors=3)

In [26]:
Y_pred = model_train.predict(X_test)

In [27]:
Y_pred

array([2, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0, 2, 1, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2,
       2, 2, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 1, 2, 0, 2, 1, 0, 0, 2,
       1, 2, 2, 0, 1, 1, 2, 0, 2, 1, 1, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 1,
       0, 1, 2, 0, 2, 0, 0, 1, 0, 0, 1, 2, 1, 1, 1, 0, 0])

In [28]:
Y_pred[0:10]

array([2, 2, 2, 1, 0, 2, 1, 0, 0, 1])

In [29]:
print(Y_test[:10])

72     1
112    2
132    2
88     1
37     0
138    2
87     1
42     0
8      0
90     1
Name: species, dtype: int64


In [30]:
i = 0;
print("\n-------------------------------------------------------------------------")
print('%-25s %-25s %-25s' % ('Original Label', 'Predicted Label', 'Correct/Wrong'))
print("\n-------------------------------------------------------------------------")
for label in Y_test:
  print('%-25s %-25s' % (label,Y_pred[i]),end="")
  if (label==Y_pred[i]):
    print(' %-25s' %('Correct'))
  else:
    print(' %-25s' %('Wrong'))
  i = i + 1
print("\n-------------------------------------------------------------------------")


-------------------------------------------------------------------------
Original Label            Predicted Label           Correct/Wrong            

-------------------------------------------------------------------------
1                         2                         Wrong                    
2                         2                         Correct                  
2                         2                         Correct                  
1                         1                         Correct                  
0                         0                         Correct                  
2                         2                         Correct                  
1                         1                         Correct                  
0                         0                         Correct                  
0                         0                         Correct                  
1                         1                         Correct           

In [31]:
import sklearn.metrics as metrics
confusion = metrics.confusion_matrix(Y_test,Y_pred)
confusion

array([[40,  0,  0],
       [ 0, 30,  1],
       [ 0,  1, 33]])

In [32]:
accuracy = accuracy_score(Y_test,Y_pred)
accuracy

0.9809523809523809

In [33]:
print('Accuracy of the classifier is %0.2f' % metrics.accuracy_score(Y_test,Y_pred))
print("\n-------------------------------------------------------------------------")

Accuracy of the classifier is 0.98

-------------------------------------------------------------------------


In [34]:
print("\nClassification Report:\n",)
class_wise=metrics.classification_report(Y_test,Y_pred)
print(class_wise)


Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.97      0.97      0.97        31
           2       0.97      0.97      0.97        34

    accuracy                           0.98       105
   macro avg       0.98      0.98      0.98       105
weighted avg       0.98      0.98      0.98       105



In [35]:
new_sample = [[5.1,3.5,1.4,0.2]]
prediction = model.predict(new_sample)
predicted_label = le.inverse_transform(prediction)
print("Predicted Class =",predicted_label)

Predicted Class = ['setosa']


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
